name: Build and Deploy to Netlify
on:
  push:
  workflow_dispatch: 
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name:  Check 1 2
        run: make env requirements check lint

  build:
    runs-on: ubuntu-latest
    needs: check    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: public-artifact
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public-artifact
          path: public/
